### PR TITLE
CONFIG_WILDCARD as array

### PR DESCRIPTION
**Pull request by valouvaliavlo**
reported by @Wouter1977 on telegram

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
Thanks @valouvaliavlo for the pull request.
This constant is used in many places around the bot and it will break if we change it this way (or we need to change the use of it as well). What is the motivation behind this change ?

**Comment by valouvaliavlo** [comment]
Mmmm yes, indeed, sorry. 
Maybe juste change the comparison on line 74 in 'octobot_trading\exchanges\exchange_config_data.py' to 'not in'.

Motivation : maybe just help

**Comment by GuillaumeDSM** [comment]
> Mmmm yes, indeed, sorry.
> Maybe juste change the comparison on line 74 in 'octobot_trading\exchanges\exchange_config_data.py' to 'not in'.
> 
> Motivation : maybe just help

Got it, thanks for the details !
We will add a new constant for wildcards in pairs config so that it doesn't conflict with others, we keep you updated :)

**Comment by GuillaumeDSM** [comment]
It's in https://github.com/Drakkar-Software/OctoBot-Commons/pull/167 and https://github.com/Drakkar-Software/OctoBot-Trading/pull/493 !

**Pull request closed without merging**
