### PR TITLE
[DataUtil] Add HL2, HLC3, OHLC4, HeikinAshi

### PR DESCRIPTION
**Pull request by valouvaliavlo**

### CODE REVIEW

**Comment by Herklos** [comment]
Nice, thank you @valouvaliavlo! Where did you find those implementations?

**Comment by Herklos** [comment]
Can you create tentacle (**Evaluator/Util**) for these indicators ? We are not implementing any indicator in Commons. We use tentacles for that.

**Comment by valouvaliavlo** [comment]
> Nice, thank you @valouvaliavlo! Where did you find those implementations?

it's from me

**Comment by valouvaliavlo** [comment]
> Can you create tentacle (**Evaluator/Util**) for these indicators ? We are not implementing any indicator in Commons. We use tentacles for that.

Ah yes !!
I forgot that

**Pull request closed without merging**
